### ISSUE TITLE
Freebase Issue

### ISSUE THREAD

**Issue by dnes85** [AKSW/DeFacto#18]
In the UI, input triples are not working when freebase URIs is present ex.: [1]. Most likely because the API is down and you can not create a dynamic model (DefactoModel) based on these resources...Any realistic and viable solution for that? 

[1] https://github.com/AKSW/FactBench/blob/master/v1/test/correct/award/award_00007.ttl

**Comment by renespeck** [comment]
The demo in the defacto-restful module, creates models in the defacto-core. If it is not working then I think the defacto-core is not supporting it. 

The given resources need to have at least the property rdfs label as far as I remember.

In the log file is a Nullpointer:
java.lang.NullPointerException
        at org.aksw.defacto.search.crawl.EvidenceCrawler.crawlEvidence(EvidenceCrawler.java:115)
Because the subject label in the model is not set. 

The solution is, for sure, to set the label correct. Not sure where the bug is. 

I copy pasted DeFacto/defacto-gui/src/main/java/org/aksw/defacto/util/DeFactoModelGenerator.java line 77 in DeFacto/defacto-restful/src/main/java/org/aksw/defacto/restful/core/RestModel.java line 168 there are DBpedia endpoints to search for the label and the given URI. I guess there it fails because of the endpoints?

**Comment by renespeck** [comment]
And in case of [1] you already have the labels so you do not need to search for them. Instead you can build the model directly. But the demo in the defacto-restful module is not build for that case.

**Comment by dnes85** [comment]
Yes, of course. But it turns out that I am implementing a new feature that must swap the resources. The main problem is that DeFacto has its model (```DefactoModel```) built up over a jena ```model``` and the current method for set a resource dynamically (subject or object, does not matter in this case) just change the resource itself (```DefactoModel``` value object), but not the extra information already existing over the jena model (the "low level" layer)!! This leads to incorrect DeFacto ```scores```. That´s why the method you created in the ```rest-module``` for dynamically generate the models would be useful (btw, we should move it later as a feature in the core layer...). Back to the ```Freebase issue```, currently (as far as I see) ```defacto-core``` module works with ```FactBench``` examples, i.e., you already have all the information needed (as you have pointed out correctly). I can extend the function I´ve created to swap that dynamically also in the jena model, but I would like to avoid that once it becomes more complex and I could just look for that information based simply in the input triple (```defacto-rest``` function). I glanced quickly at the ```run-time``` implementation to generate the model and the error seems to be exactly that, for DBPedia resources you get the information, but looks like the method ```protected Model generateModel(Set<String> uris, Set<String> langs)```isn't covering ```Freebase``` resources. Do we have a ```FreeBase``` endpoint somewhere?

**Comment by dnes85** [comment]
I see 2 options here: I can either extend your script (```defacto-rest```) to cover ```Freebase``` resources (dynamically) or extend mine at ```defacto-core``` level and update the jena model as well (the drawback is that, in the end, it would cover just ```FactBench``` examples...)

**Comment by renespeck** [comment]
Here is an endpoint: http://factforge.net/sparql.But I don't know what is the best option to fix the issue.

**Comment by dnes85** [comment]
Solved: eba8efb
